; ----------------------------------
; Zombie Plague 4.3 Extra Items File
; ----------------------------------
; Any changes you make here will be
; automatically loaded at map start

; This file will be automatically updated with new
; editable entries as you install new custom items.

[Armura (100ap)]
NAME = Armura (100ap)
COST = 5
TEAMS = HUMAN

[Armura (200ap)]
NAME = Armura (200ap)
COST = 10
TEAMS = HUMAN

[\r[\wBalrogm4\r]]
NAME = \r[\wBalrogm4\r]
COST = 85
TEAMS = HUMAN

[bak47p]
NAME = bak47p
COST = 45
TEAMS = HUMAN

[Scar Born Beast]
NAME = Scar Born Beast
COST = 30
TEAMS = HUMAN

[\r[\wSprifle\r]]
NAME = \r[\wSprifle\r]
COST = 39
TEAMS = HUMAN

[AK-47 Transformers]
NAME = AK-47 Transformers
COST = 2
TEAMS = HUMAN

[AK47 Beast]
NAME = AK47 Beast
COST = 0
TEAMS = HUMAN

[Zombie-Amxx.Ru - Frost M4A1]
NAME = Zombie-Amxx.Ru - Frost M4A1
COST = 30
TEAMS = HUMAN

[No Recoil]
NAME = No Recoil
COST = 15
TEAMS = HUMAN

[M4A1-S Angelic Beast]
NAME = M4A1-S Angelic Beast
COST = 85
TEAMS = HUMAN

[Zombie-Amxx.Ru - FrozenLava M4]
NAME = Zombie-Amxx.Ru - FrozenLava M4
COST = 120
TEAMS = HUMAN

[M4A1-S Iron Beast]
NAME = M4A1-S Iron Beast
COST = 85
TEAMS = HUMAN

[\r[\wAT15 HW\r]]
NAME = \r[\wAT15 HW\r]
COST = 43
TEAMS = HUMAN
